workflows:
    android-workflow-id:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
    ios-workflow-id:
        name: iOS Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
